//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RoomCourseModel", "LevelRoom", "Level", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FhvRoomSearch.Model.Level), "Room", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FhvRoomSearch.Model.Room))]
[assembly: EdmRelationshipAttribute("RoomCourseModel", "WingLevel", "Wing", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FhvRoomSearch.Model.Wing), "Level", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FhvRoomSearch.Model.Level))]
[assembly: EdmRelationshipAttribute("RoomCourseModel", "RoomCourse", "Room", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FhvRoomSearch.Model.Room), "Course", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FhvRoomSearch.Model.Course))]

#endregion

namespace FhvRoomSearch.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RoomCourseModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RoomCourseModelContainer object using the connection string found in the 'RoomCourseModelContainer' section of the application configuration file.
        /// </summary>
        public RoomCourseModelContainer() : base("name=RoomCourseModelContainer", "RoomCourseModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RoomCourseModelContainer object.
        /// </summary>
        public RoomCourseModelContainer(string connectionString) : base(connectionString, "RoomCourseModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RoomCourseModelContainer object.
        /// </summary>
        public RoomCourseModelContainer(EntityConnection connection) : base(connection, "RoomCourseModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Room> RoomSet
        {
            get
            {
                if ((_RoomSet == null))
                {
                    _RoomSet = base.CreateObjectSet<Room>("RoomSet");
                }
                return _RoomSet;
            }
        }
        private ObjectSet<Room> _RoomSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Level> LevelSet
        {
            get
            {
                if ((_LevelSet == null))
                {
                    _LevelSet = base.CreateObjectSet<Level>("LevelSet");
                }
                return _LevelSet;
            }
        }
        private ObjectSet<Level> _LevelSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Wing> WingSet
        {
            get
            {
                if ((_WingSet == null))
                {
                    _WingSet = base.CreateObjectSet<Wing>("WingSet");
                }
                return _WingSet;
            }
        }
        private ObjectSet<Wing> _WingSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Course> CourseSet
        {
            get
            {
                if ((_CourseSet == null))
                {
                    _CourseSet = base.CreateObjectSet<Course>("CourseSet");
                }
                return _CourseSet;
            }
        }
        private ObjectSet<Course> _CourseSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Config> ConfigSet
        {
            get
            {
                if ((_ConfigSet == null))
                {
                    _ConfigSet = base.CreateObjectSet<Config>("ConfigSet");
                }
                return _ConfigSet;
            }
        }
        private ObjectSet<Config> _ConfigSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoomSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoomSet(Room room)
        {
            base.AddObject("RoomSet", room);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LevelSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLevelSet(Level level)
        {
            base.AddObject("LevelSet", level);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WingSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWingSet(Wing wing)
        {
            base.AddObject("WingSet", wing);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CourseSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseSet(Course course)
        {
            base.AddObject("CourseSet", course);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConfigSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigSet(Config config)
        {
            base.AddObject("ConfigSet", config);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RoomCourseModel", Name="Config")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Config : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Config object.
        /// </summary>
        /// <param name="key">Initial value of the Key property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static Config CreateConfig(global::System.String key, global::System.String value)
        {
            Config config = new Config();
            config.Key = key;
            config.Value = value;
            return config;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                if (_Key != value)
                {
                    OnKeyChanging(value);
                    ReportPropertyChanging("Key");
                    _Key = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Key");
                    OnKeyChanged();
                }
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RoomCourseModel", Name="Course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Course : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="startTime">Initial value of the StartTime property.</param>
        /// <param name="endTime">Initial value of the EndTime property.</param>
        public static Course CreateCourse(global::System.Int32 id, global::System.DateTime startTime, global::System.DateTime endTime)
        {
            Course course = new Course();
            course.Id = id;
            course.StartTime = startTime;
            course.EndTime = endTime;
            return course;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private global::System.DateTime _EndTime;
        partial void OnEndTimeChanging(global::System.DateTime value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category = "";
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes = "";
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Module
        {
            get
            {
                return _Module;
            }
            set
            {
                OnModuleChanging(value);
                ReportPropertyChanging("Module");
                _Module = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Module");
                OnModuleChanged();
            }
        }
        private global::System.String _Module = "";
        partial void OnModuleChanging(global::System.String value);
        partial void OnModuleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lecturer
        {
            get
            {
                return _Lecturer;
            }
            set
            {
                OnLecturerChanging(value);
                ReportPropertyChanging("Lecturer");
                _Lecturer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lecturer");
                OnLecturerChanged();
            }
        }
        private global::System.String _Lecturer = "";
        partial void OnLecturerChanging(global::System.String value);
        partial void OnLecturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Group
        {
            get
            {
                return _Group;
            }
            set
            {
                OnGroupChanging(value);
                ReportPropertyChanging("Group");
                _Group = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Group");
                OnGroupChanged();
            }
        }
        private global::System.String _Group = "";
        partial void OnGroupChanging(global::System.String value);
        partial void OnGroupChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RoomCourseModel", "RoomCourse", "Room")]
        public EntityCollection<Room> Rooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Room>("RoomCourseModel.RoomCourse", "Room");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Room>("RoomCourseModel.RoomCourse", "Room", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RoomCourseModel", Name="Level")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Level : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Level object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Level CreateLevel(global::System.Int32 id, global::System.String name)
        {
            Level level = new Level();
            level.Id = id;
            level.Name = name;
            return level;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RoomCourseModel", "LevelRoom", "Room")]
        public EntityCollection<Room> Room
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Room>("RoomCourseModel.LevelRoom", "Room");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Room>("RoomCourseModel.LevelRoom", "Room", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RoomCourseModel", "WingLevel", "Wing")]
        public Wing Wing
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wing>("RoomCourseModel.WingLevel", "Wing").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wing>("RoomCourseModel.WingLevel", "Wing").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Wing> WingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Wing>("RoomCourseModel.WingLevel", "Wing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Wing>("RoomCourseModel.WingLevel", "Wing", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RoomCourseModel", Name="Room")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Room : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Room object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="roomId">Initial value of the RoomId property.</param>
        /// <param name="roomName">Initial value of the RoomName property.</param>
        /// <param name="tables">Initial value of the Tables property.</param>
        /// <param name="chairs">Initial value of the Chairs property.</param>
        /// <param name="computers">Initial value of the Computers property.</param>
        /// <param name="extrasValue">Initial value of the ExtrasValue property.</param>
        /// <param name="chairTypeValue">Initial value of the ChairTypeValue property.</param>
        public static Room CreateRoom(global::System.Int32 id, global::System.String roomId, global::System.String roomName, global::System.Int32 tables, global::System.Int32 chairs, global::System.Int32 computers, global::System.Int32 extrasValue, global::System.Int32 chairTypeValue)
        {
            Room room = new Room();
            room.Id = id;
            room.RoomId = roomId;
            room.RoomName = roomName;
            room.Tables = tables;
            room.Chairs = chairs;
            room.Computers = computers;
            room.ExtrasValue = extrasValue;
            room.ChairTypeValue = chairTypeValue;
            return room;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoomId
        {
            get
            {
                return _RoomId;
            }
            set
            {
                OnRoomIdChanging(value);
                ReportPropertyChanging("RoomId");
                _RoomId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoomId");
                OnRoomIdChanged();
            }
        }
        private global::System.String _RoomId;
        partial void OnRoomIdChanging(global::System.String value);
        partial void OnRoomIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoomName
        {
            get
            {
                return _RoomName;
            }
            set
            {
                OnRoomNameChanging(value);
                ReportPropertyChanging("RoomName");
                _RoomName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoomName");
                OnRoomNameChanged();
            }
        }
        private global::System.String _RoomName;
        partial void OnRoomNameChanging(global::System.String value);
        partial void OnRoomNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tables
        {
            get
            {
                return _Tables;
            }
            set
            {
                OnTablesChanging(value);
                ReportPropertyChanging("Tables");
                _Tables = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tables");
                OnTablesChanged();
            }
        }
        private global::System.Int32 _Tables;
        partial void OnTablesChanging(global::System.Int32 value);
        partial void OnTablesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Chairs
        {
            get
            {
                return _Chairs;
            }
            set
            {
                OnChairsChanging(value);
                ReportPropertyChanging("Chairs");
                _Chairs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Chairs");
                OnChairsChanged();
            }
        }
        private global::System.Int32 _Chairs;
        partial void OnChairsChanging(global::System.Int32 value);
        partial void OnChairsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Computers
        {
            get
            {
                return _Computers;
            }
            set
            {
                OnComputersChanging(value);
                ReportPropertyChanging("Computers");
                _Computers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Computers");
                OnComputersChanged();
            }
        }
        private global::System.Int32 _Computers;
        partial void OnComputersChanging(global::System.Int32 value);
        partial void OnComputersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExtrasValue
        {
            get
            {
                return _ExtrasValue;
            }
            set
            {
                OnExtrasValueChanging(value);
                ReportPropertyChanging("ExtrasValue");
                _ExtrasValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExtrasValue");
                OnExtrasValueChanged();
            }
        }
        private global::System.Int32 _ExtrasValue;
        partial void OnExtrasValueChanging(global::System.Int32 value);
        partial void OnExtrasValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChairTypeValue
        {
            get
            {
                return _ChairTypeValue;
            }
            set
            {
                OnChairTypeValueChanging(value);
                ReportPropertyChanging("ChairTypeValue");
                _ChairTypeValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChairTypeValue");
                OnChairTypeValueChanged();
            }
        }
        private global::System.Int32 _ChairTypeValue;
        partial void OnChairTypeValueChanging(global::System.Int32 value);
        partial void OnChairTypeValueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RoomCourseModel", "LevelRoom", "Level")]
        public Level Level
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Level>("RoomCourseModel.LevelRoom", "Level").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Level>("RoomCourseModel.LevelRoom", "Level").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Level> LevelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Level>("RoomCourseModel.LevelRoom", "Level");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Level>("RoomCourseModel.LevelRoom", "Level", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RoomCourseModel", "RoomCourse", "Course")]
        public EntityCollection<Course> Course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Course>("RoomCourseModel.RoomCourse", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Course>("RoomCourseModel.RoomCourse", "Course", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RoomCourseModel", Name="Wing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Wing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Wing object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Wing CreateWing(global::System.Int32 id, global::System.String name)
        {
            Wing wing = new Wing();
            wing.Id = id;
            wing.Name = name;
            return wing;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RoomCourseModel", "WingLevel", "Level")]
        public EntityCollection<Level> Level
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Level>("RoomCourseModel.WingLevel", "Level");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Level>("RoomCourseModel.WingLevel", "Level", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
