//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FhvRoomSearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FhvRoomSearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///--&gt;
        ///&lt;ArrayOfWing&gt;
        ///  &lt;Wing Name=&quot;A&quot;&gt;
        ///    &lt;Level Name=&quot;A0&quot;&gt;
        ///      &lt;Room RoomId=&quot;Aula&quot; RoomName=&quot;Veranstaltungssaal&quot; Tables=&quot;0&quot; Chairs=&quot;178&quot; Computers=&quot;0&quot; Extras=&quot;Projector, Speaker, Microphone, SilverScreen&quot; ChairType=&quot;Cinema&quot; /&gt;
        ///    &lt;/Level&gt;
        ///  &lt;/Wing&gt;
        ///  &lt;Wing Name=&quot;B&quot;&gt;
        ///    &lt;Level Name=&quot;B0&quot; /&gt;
        ///    &lt;Level Name=&quot;B1&quot;&gt;
        ///      &lt;Room RoomId=&quot;B102 (PBL)&quot; RoomName=&quot;PBL&quot; Tables=&quot;0&quot; Chairs=&quot;28&quot; Computers=&quot;0&quot; Extras=&quot;Blackboard, Projector, Speaker, Overhead&quot; ChairT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultWingData {
            get {
                return ResourceManager.GetString("DefaultWingData", resourceCulture);
            }
        }
    }
}
